server{
	listen 443 ssl;
	server_name efittant.42.fr;

	ssl_certificate /etc/nginx/ssl/cert.crt;
	ssl_certificate_key /etc/nginx/ssl/cert.key;
	
	#SSL secure socket layer
	#TLS transport layer security
	ssl_protocols TLSv1.2 TLSv1.3;
	
	root /var/www/html;
	index index.php index.html;
	
	location \ {
		#it tries to go to the requested page, if not existing goes back to index.php (keeping the arguments ($arg))
		#uri si the path user requested
		try_files $uri $uri/ /index.php?$args;
	}
	
	location ~ \.php$ {
		#fastcgi is a communication protocol between web server and program (php-fpm - which executes php code)
		include fastcgi_params;	
		fastcgi_pass wordpress:9000;
		#this tells php-fpm the full file path to execute:
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}
}