#build → build image from your Dockerfile
#image → resulting image name
#ports → expose only nginx to host
#volumes → mount named volumes into container paths
#networks → connect service to that network
#env_file → load variables from .env

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports: 
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
     - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
     - mariadb
    
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    env_file: .env
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/efittant/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/efittant/data/mariadb

networks:
  inception:
    name: inception